services:
    flerex.linkedaccounts.listener:
        class: flerex\linkedaccounts\event\main_listener
        arguments:
            - '@user'
            - '@template'
        tags:
            - { name: event.listener }